env:
  jest: true

extends:
  - airbnb-base
  - plugin:flowtype/recommended
  - prettier
  - prettier/flowtype

parser: babel-eslint

plugins:
  - flowtype

rules:
  no-restricted-syntax:
    - error
    - message: for..in loops iterate over the entire prototype chain, which is virtually
        never what you want. Use Object.{keys,values,entries}, and iterate over the resulting
        array.
      selector: ForInStatement
    - message: Labels are a form of GOTO; using them makes code confusing and hard to
        maintain and understand.
      selector: LabeledStatement
    - message: "`with` is disallowed in strict mode because it makes code impossible to
        predict and optimize."
      selector: WithStatement
